use_frameworks!

target 'MVVMR_Example' do
  pod 'MVVMR', :path => '../'
  pod 'SimpleTwoWayBinding', :git => 'https://github.com/alinradut/SimpleTwoWayBindingIOS.git'
  pod 'MBProgressHUD'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'FontAwesome.swift'
end
