use_frameworks!

target 'MVVMR_Example' do
  pod 'MVVMR', :path => '../'
  pod 'SimpleTwoWayBinding', :git => 'https://github.com/alinradut/SimpleTwoWayBindingIOS.git'
  pod 'MBProgressHUD'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'FontAwesome.swift'

  target 'MVVMR_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
